### ISSUE TITLE
No such file: "arch_cfg.yaml"

### ISSUE THREAD

**Issue by yutouwd** [HITSZ-NRSL/long-term-localization#1]
Hello @lisilin013.

Thanks for your outstanding work. I have successfully built this project and run the first step. But when I try to run `./sh/offline_process.sh` it would have the error:
```
[Errno 2] No such file or directory: '../../../model/trunk_pole/arch_cfg.yaml'
```

Would you like to provide that file? Thanks a lot.

**Comment by lisilin013** [comment]
Sorry about that.
The `model` folder is ignored  at `https://github.com/HITSZ-NRSL/long-term-localization/blob/master/src/other_pkgs/lidar-bonnetal/.gitignore`.

@nixwang Can you upload that `model` folder? I have lost that folder in my PC.

**Comment by nixwang** [comment]
The model folder has uploaded to the cloud file, please refer to "3.1 Semantic Processing" in README.md. @yutouwd

**Comment by yutouwd** [comment]
Thanks for providing the model :)

**Comment by arjunskumar** [comment]
@nixwang could you share the model and bag files?

**Comment by nixwang** [comment]
Sorry for waiting, the link of model and bag file has been updated.
