### ISSUE TITLE
Bag Unindexed Exception

### ISSUE THREAD

**Issue by yutouwd** [HITSZ-NRSL/long-term-localization#2]
Hello，

When running the `offline_process.sh` and after getting the label, it seems still has some error on writing the semantic topic into the rosbag. The command line output is as followed:

```
Infered seq 00 scan 000230.label in 5.8387532234191895 sec
/home/yutouwd/logs/sequences/00/predictions/000230.label
Infered seq 00 scan 000231.label in 5.711495637893677 sec
/home/yutouwd/logs/sequences/00/predictions/000231.label
Finished Infering
copy predictions to labels...
write semantic cloud and pose to rosbag...
terminate called after throwing an instance of 'rosbag::BagUnindexedException'
  what():  Bag unindexed
./sh/offline_process.sh: line 21: 29778 Aborted                 (core dumped) rosrun long_term_relocalization semantic_bag_writer_main --dataset_dir ~/offline_process/sequences/00/
offline process done
```

Could you please give some suggestions to fix it?

**Comment by nixwang** [comment]
There is no error in my new desktop after testing many times. 
And I suggest that you may run the process again from the start(run lio_sam and record.sh again), this works for someone.
Feel free to comment any time.

**Comment by nixwang** [comment]
And the pytorch should be the version of gpu, this can accurate the process of offline_process. @yutouwd
