### ISSUE TITLE
Model link invalid

### ISSUE THREAD

**Issue by wangchen-1994** [HITSZ-NRSL/long-term-localization#4]
Hi all:
Could you offer a new link for your model? The old one (https://www.jianguoyun.com/p/DUoZpFUQ84SvCRjL2OsD (Access Password：nros2021) is deprecated now.

**Comment by nixwang** [comment]
The addtional google drive link of the model is updated.
[https://drive.google.com/file/d/1d7nw5IuQdAzLGRM5W_cP4LZbxnh2_3lw/view?usp=sharing](https://drive.google.com/file/d/1d7nw5IuQdAzLGRM5W_cP4LZbxnh2_3lw/view?usp=sharing)
@wangchen-1994
